---
title: Copies EntiForWin Readme
description: Copies EntiForWin Readme to users desktop
actions:
  - !cmd:
    command: 'copy /y "AtmosphereReadme.txt" "%userprofile%\Desktop\README.txt"'
    exeDir: true
    wait: true